language: ruby
rvm:
  - jruby-19mode
  - jruby-head
  - 1.9.3

matrix:
  allow_failures:
    - rvm: 1.9.3

jdk:
  - openjdk7

sudo: false

before_install: gem install bundler -v 1.10.3

install: travis_retry bundle install

before_script: bundle exec rake build

script:
  - bundle exec rake spec
branches:
  only:
    - master
